### ISSUE TITLE
Full QA cross-browser testing. 

### ISSUE THREAD

**Issue by ACSCORP** [ACSCORP/ALCOLOCK-myprogram-website#1]
(Specifically Internet Explorer and older versions of Internet Explorer).

**Comment by ACSCORP** [comment]
Suggest various tools for this: 

http://mashable.com/2014/02/26/browser-testing-tools/#nYEiehDUhGqm

**Comment by kr1st1n4gr03g3r** [comment]
Duplicate. Close.
