### ISSUE TITLE
Product List

### ISSUE THREAD

**Issue by ACSCORP** [ACSCORP/ALCOLOCK-myprogram-website#14]
Remove all caps and bold from product list. Use title case to maintain consistency.

![screen shot 2016-01-13 at 3 27 17 pm](https://cloud.githubusercontent.com/assets/16691301/12306953/80302c7c-ba0a-11e5-98b0-0e409c12ef5a.jpg)

**Comment by kr1st1n4gr03g3r** [comment]
Close
