### ISSUE TITLE
"CHECK OUT"

### ISSUE THREAD

**Issue by ACSCORP** [ACSCORP/ALCOLOCK-myprogram-website#15]
Checkout is one word. Change on checkout page, title and button. (Keep checkout icon).

![screen shot 2016-01-13 at 3 31 18 pm](https://cloud.githubusercontent.com/assets/16691301/12306984/a72e1b86-ba0a-11e5-83c8-20788364eb55.png)

**Comment by kr1st1n4gr03g3r** [comment]
Close
