### ISSUE TITLE
Spacing Consistency

### ISSUE THREAD

**Issue by ACSCORP** [ACSCORP/ALCOLOCK-myprogram-website#17]
Add space to contacts as the other icons are spaced

![screen shot 2016-01-13 at 3 39 34 pm](https://cloud.githubusercontent.com/assets/16691301/12307198/c8f6e88c-ba0b-11e5-8ca4-f7d18877f4f4.png)

**Comment by kr1st1n4gr03g3r** [comment]
Henry will fix
