### ISSUE TITLE
Language Switch

### ISSUE THREAD

**Issue by ACSCORP** [ACSCORP/ALCOLOCK-myprogram-website#19]
Remove EN with icon and keep the dropdown

Add translations or don't add option for French.

![screen shot 2016-01-13 at 3 39 34 pm](https://cloud.githubusercontent.com/assets/16691301/12307351/c6269e62-ba0c-11e5-8897-f2f0bf8a6157.png)

**Comment by kr1st1n4gr03g3r** [comment]
Close
