### ISSUE TITLE
Text Size Consistency

### ISSUE THREAD

**Issue by ACSCORP** [ACSCORP/ALCOLOCK-myprogram-website#20]
Maintain text sizing consistency in all dropdowns and tables. EG: Text in date fields should match the rest of the text on this page.

![screen shot 2016-01-13 at 3 48 26 pm](https://cloud.githubusercontent.com/assets/16691301/12307420/26f9e96a-ba0d-11e5-8de3-64ff77ffbbb4.png)

**Comment by kr1st1n4gr03g3r** [comment]
Henry did this yes.

**Comment by kr1st1n4gr03g3r** [comment]
Close
