### ISSUE TITLE
Site-wide Alignment Issues

### ISSUE THREAD

**Issue by ACSCORP** [ACSCORP/ALCOLOCK-myprogram-website#8]
Alignment changes across the website as per meeting with Denise today.

Text should all be consistently aligned left (see highlights in pink)

![screen shot 2016-01-13 at 3 09 54 pm](https://cloud.githubusercontent.com/assets/16691301/12306540/57a08dd0-ba08-11e5-97ce-5331d7f8461f.jpg)
![screen shot 2016-01-13 at 3 10 00 pm](https://cloud.githubusercontent.com/assets/16691301/12306536/579f021c-ba08-11e5-9675-1964c26525a5.jpg)
![screen shot 2016-01-13 at 3 10 16 pm](https://cloud.githubusercontent.com/assets/16691301/12306539/579f3f2a-ba08-11e5-93d9-44ae76552c0e.jpg)
![screen shot 2016-01-13 at 3 10 12 pm](https://cloud.githubusercontent.com/assets/16691301/12306535/579c5a9e-ba08-11e5-8748-44d14e9e1e51.jpg)
![screen shot 2016-01-13 at 3 10 07 pm](https://cloud.githubusercontent.com/assets/16691301/12306538/579f54b0-ba08-11e5-9aac-e1813dc8f5c9.jpg)
![screen shot 2016-01-13 at 3 09 48 pm](https://cloud.githubusercontent.com/assets/16691301/12306537/579f553c-ba08-11e5-817d-bcf7216888fd.jpg)

**Comment by kr1st1n4gr03g3r** [comment]
Very table mad left align txt
