### ISSUE TITLE
Remove "s" from catchphrase "roads"

### ISSUE THREAD

**Issue by ACSCORP** [ACSCORP/ALCOLOCK-myprogram-website#9]
Catchphrase should read "keeping you safe on the road"

![screen shot 2016-01-13 at 3 16 21 pm](https://cloud.githubusercontent.com/assets/16691301/12306654/cdfb849e-ba08-11e5-98a5-4b21d73379f5.jpg)

**Comment by kr1st1n4gr03g3r** [comment]
Ingrid to give
